/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zhJZe9nw73f
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function BlowMartysMind() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="flex items-center h-14 px-4 border-b lg:px-6">
        <div className="container flex items-center gap-4">
          <Link className="flex items-center gap-2 font-semibold" href="#">
            <Package2Icon className="h-6 w-6" />
            <span className="">Acme Inc</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6 lg:gap-4 xl:gap-8">
            <Link className="font-medium" href="#">
              Men's
            </Link>
            <Link className="font-medium" href="#">
              Women's
            </Link>
            <Link className="font-medium" href="#">
              Kids
            </Link>
            <Link className="font-medium" href="#">
              Accessories
            </Link>
          </nav>
          <div className="ml-auto flex items-center gap-4 lg:gap-2">
            <form className="hidden md:flex items-center gap-2 lg:ml-auto">
              <Label className="sr-only" htmlFor="search">
                Search
              </Label>
              <Input
                className="w-[200px] h-9 border-gray-200 rounded-lg dark:border-gray-800"
                id="search"
                placeholder="Search..."
                type="search"
              />
              <Button size="sm" type="submit" variant="icon">
                <SearchIcon className="w-4 h-4" />
                <span className="sr-only">Search</span>
              </Button>
            </form>
            <Button className="hidden md:block" size="sm" variant="outline">
              Contact
            </Button>
            <Button className="hidden md:block" size="sm" variant="outline">
              Cart
            </Button>
            <Button className="md:hidden" size="sm" variant="outline">
              <MenuIcon className="w-4 h-4" />
              <span className="sr-only">Toggle menu</span>
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1 flex flex-col">
        <section className="grid items-center py-12 gap-4 text-center md:py-16 lg:py-24 xl:gap-8">
          <div className="container flex flex-col items-center gap-4 px-4 md:px-6 lg:gap-8 xl:grid xl:grid-cols-2 xl:items-center xl:gap-12">
            <div className="space-y-4 xl:order-1 xl:text-right">
              <h1 className="text-4xl font-bold tracking-tighter lg:text-6xl xl:text-7xl/none">Adventure Awaits</h1>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Shop the best selection of snowboards. Fast, free shipping on all orders.
              </p>
            </div>
            <img
              alt="Snowboard"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center xl:order-2"
              height="400"
              src="/placeholder.svg"
              width="600"
            />
          </div>
          <div className="border-t border-gray-200 w-full dark:border-gray-800" />
        </section>
        <section className="py-12 md:py-16 lg:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid items-start gap-6 lg:grid-cols-3 lg:gap-10">
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-24 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid items-start gap-6 lg:grid-cols-3 lg:gap-10">
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid items-start gap-6 lg:grid-cols-3 lg:gap-10">
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid items-start gap-6 lg:grid-cols-3 lg:gap-10">
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
              <div className="flex items-center justify-center aspect-video rounded-lg overflow-hidden">
                <img
                  alt="Image"
                  className="object-cover object-center"
                  height="225"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/225",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex items-center justify-center h-20 px-4 border-t md:px-6">
        <div className="container flex items-center justify-center gap-4 text-sm">
          <span className="text-gray-500 dark:text-gray-400">© 2023 Acme Inc. All rights reserved.</span>
          <nav className="flex gap-4">
            <Link className="underline underline-offset-2" href="#">
              Terms & Conditions
            </Link>
            <Link className="underline underline-offset-2" href="#">
              Privacy Policy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
